exports.test = [
   {
      id: 'imm 1',
      team: 'immune',
      units: 17,
      hp: 5390,
      immunities: [],
      weaknesses: ['radiation', 'bludgeoning'],
      attack: 4507,
      attackType: 'fire',
      initiative: 2,
   },
   {
      id: 'imm 2',
      team: 'immune',
      units: 989,
      hp: 1274,
      immunities: ['fire'],
      weaknesses: ['bludgeoning', 'slashing'],
      attack: 25,
      attackType: 'slashing',
      initiative: 3,
   },
   {
      id: 'inf 1',
      team: 'infection',
      units: 801,
      hp: 4706,
      immunities: [],
      weaknesses: ['radiation'],
      attack: 116,
      attackType: 'bludgeoning',
      initiative: 1,
   },
   {
      id: 'inf 2',
      team: 'infection',
      units: 4485,
      hp: 2961,
      immunities: ['radiation'],
      weaknesses: ['fire', 'cold'],
      attack: 12,
      attackType: 'slashing',
      initiative: 4,
   }
];

exports.real = [
   {
      id: 'real',
      team: 'immune',
      units: 2728,
      hp: 5703,
      immunities: [],
      weaknesses: ['fire'],
      attack: 18,
      attackType: 'cold',
      initiative: 12,
   },
   {
      id: 'real',
      team: 'immune',
      units: 916,
      hp: 5535,
      immunities: [],
      weaknesses: ['bludgeoning'],
      attack: 55,
      attackType: 'slashing',
      initiative: 20,
   },
   {
      id: 'real',
      team: 'immune',
      units: 2255,
      hp: 7442,
      immunities: [],
      weaknesses: ['radiation'],
      attack: 31,
      attackType: 'bludgeoning',
      initiative: 8,
   },
   {
      id: 'real',
      team: 'immune',
      units: 112,
      hp: 4951,
      immunities: ['cold'],
      weaknesses: [],
      attack: 360,
      attackType: 'fire',
      initiative: 9,
   },
   {
      id: 'real',
      team: 'immune',
      units: 7376,
      hp: 6574,
      immunities: ['cold', 'slashing', 'fire'],
      weaknesses: [],
      attack: 7,
      attackType: 'bludgeoning',
      initiative: 4,
   },
   {
      id: 'real',
      team: 'immune',
      units: 77,
      hp: 5884,
      immunities: [],
      weaknesses: ['slashing'],
      attack: 738,
      attackType: 'radiation',
      initiative: 6,
   },
   {
      id: 'real',
      team: 'immune',
      units: 6601,
      hp: 8652,
      immunities: [],
      weaknesses: ['fire', 'cold'],
      attack: 11,
      attackType: 'fire',
      initiative: 19,
   },
   {
      id: 'real',
      team: 'immune',
      units: 3259,
      hp: 10067,
      immunities: [],
      weaknesses: ['bludgeoning'],
      attack: 29,
      attackType: 'cold',
      initiative: 13,
   },
   {
      id: 'real',
      team: 'immune',
      units: 2033,
      hp: 4054,
      immunities: ['cold'],
      weaknesses: ['fire', 'slashing'],
      attack: 18,
      attackType: 'slashing',
      initiative: 3,
   },
   {
      id: 'real',
      team: 'immune',
      units: 3109,
      hp: 3593,
      immunities: [],
      weaknesses: [],
      attack: 9,
      attackType: 'bludgeoning',
      initiative: 11,
   },





   {
      id: 'real',
      team: 'infection',
      units: 1466,
      hp: 57281,
      immunities: [],
      weaknesses: ['slashing', 'fire'],
      attack: 58,
      attackType: 'slashing',
      initiative: 7,
   },
   {
      id: 'real',
      team: 'infection',
      units: 247,
      hp: 13627,
      immunities: [],
      weaknesses: [],
      attack: 108,
      attackType: 'fire',
      initiative: 15,
   },
   {
      id: 'real',
      team: 'infection',
      units: 1298,
      hp: 41570,
      immunities: ['fire', 'bludgeoning'],
      weaknesses: [],
      attack: 63,
      attackType: 'fire',
      initiative: 14,
   },
   {
      id: 'real',
      team: 'infection',
      units: 2161,
      hp: 40187,
      immunities: [],
      weaknesses: ['fire'],
      attack: 33,
      attackType: 'slashing',
      initiative: 5,
   },
   {
      id: 'real',
      team: 'infection',
      units: 57,
      hp: 55432,
      immunities: [],
      weaknesses: ['cold'],
      attack: 1687,
      attackType: 'radiation',
      initiative: 17,
   },
   {
      id: 'real',
      team: 'infection',
      units: 3537,
      hp: 24220,
      immunities: [],
      weaknesses: ['cold'],
      attack: 11,
      attackType: 'fire',
      initiative: 10,
   },
   {
      id: 'real',
      team: 'infection',
      units: 339,
      hp: 44733,
      immunities: ['cold', 'bludgeoning'],
      weaknesses: ['radiation', 'fire'],
      attack: 258,
      attackType: 'cold',
      initiative: 18,
   },
   {
      id: 'real',
      team: 'infection',
      units: 1140,
      hp: 17741,
      immunities: ['fire', 'slashing'],
      weaknesses: ['bludgeoning'],
      attack: 25,
      attackType: 'fire',
      initiative: 2,
   },
   {
      id: 'real',
      team: 'infection',
      units: 112,
      hp: 44488,
      immunities: ['cold'],
      weaknesses: ['bludgeoning', 'radiation'],
      attack: 749,
      attackType: 'radiation',
      initiative: 16,
   },
   {
      id: 'real',
      team: 'infection',
      units: 2918,
      hp: 36170,
      immunities: ['bludgeoning'],
      weaknesses: ['slashing', 'cold'],
      attack: 24,
      attackType: 'radiation',
      initiative: 1,
   },
];
