exports.test = [
  {'match':'...##', 'becomes':'#'},
  {'match':'..#..', 'becomes':'#'},
  {'match':'.#...', 'becomes':'#'},
  {'match':'.#.#.', 'becomes':'#'},
  {'match':'.#.##', 'becomes':'#'},
  {'match':'.##..', 'becomes':'#'},
  {'match':'.####', 'becomes':'#'},
  {'match':'#.#.#', 'becomes':'#'},
  {'match':'#.###', 'becomes':'#'},
  {'match':'##.#.', 'becomes':'#'},
  {'match':'##.##', 'becomes':'#'},
  {'match':'###..', 'becomes':'#'},
  {'match':'###.#', 'becomes':'#'},
  {'match':'####.', 'becomes':'#'}
];

exports.real = [
  {'match':'##...', 'becomes':'.'},
  {'match':'....#', 'becomes':'.'},
  {'match':'#.##.', 'becomes':'.'},
  {'match':'.....', 'becomes':'.'},
  {'match':'..###', 'becomes':'.'},
  {'match':'###..', 'becomes':'.'},
  {'match':'#..#.', 'becomes':'#'},
  {'match':'##.##', 'becomes':'.'},
  {'match':'...##', 'becomes':'#'},
  {'match':'#..##', 'becomes':'.'},
  {'match':'#.###', 'becomes':'.'},
  {'match':'#.#.#', 'becomes':'#'},
  {'match':'####.', 'becomes':'.'},
  {'match':'.###.', 'becomes':'#'},
  {'match':'.##.#', 'becomes':'.'},
  {'match':'##.#.', 'becomes':'#'},
  {'match':'...#.', 'becomes':'.'},
  {'match':'.#.#.', 'becomes':'.'},
  {'match':'#...#', 'becomes':'#'},
  {'match':'#####', 'becomes':'#'},
  {'match':'..#..', 'becomes':'.'},
  {'match':'..#.#', 'becomes':'#'},
  {'match':'..##.', 'becomes':'.'},
  {'match':'###.#', 'becomes':'#'},
  {'match':'.####', 'becomes':'#'},
  {'match':'#....', 'becomes':'.'},
  {'match':'.#..#', 'becomes':'#'},
  {'match':'.##..', 'becomes':'#'},
  {'match':'#.#..', 'becomes':'#'},
  {'match':'##..#', 'becomes':'.'},
  {'match':'.#...', 'becomes':'#'},
  {'match':'.#.##', 'becomes':'#'}
];
